import './globals.css';
import Sidebar from '@/components/Sidebar';

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME || 'Simple Finance',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className="min-h-screen bg-zinc-50 text-zinc-900">
        <div className="mx-auto max-w-6xl p-6">
          <header className="mb-6 flex items-center justify-between">
            <h1 className="text-xl font-semibold tracking-tight">
              {process.env.NEXT_PUBLIC_APP_NAME || 'Simple Finance'}
            </h1>
            <nav className="text-sm text-zinc-600">v1</nav>
          </header>

          <div className="grid gap-6 md:grid-cols-[14rem_1fr]">
            {/* Sidebar (stacked on mobile) */}
            <Sidebar />
            {/* Main content */}
            <div className="space-y-6">{children}</div>
          </div>

          <footer className="mt-10 text-center text-xs text-zinc-500">
            Built with Next.js + Prisma + Tailwind
          </footer>
        </div>
      </body>
    </html>
  );
}



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
